### ISSUE TITLE
requirements/base.txt specifies old version of Django 1.8

### ISSUE THREAD

**Issue by brycenesbitt** [fasouto/django-starter-template#1]
This pulls in an old version of Django... for a new project it seems the latest release would be better?

    # Basic stuff
    Django=1.8

**Comment by fasouto** [comment]
Yes, you are right. It's fixed now.

Thank you!

**Comment by brycenesbitt** [comment]
The same issue exists for all the modules.  Best practice is generally to start with the latest version, but at some point freeze versions.

**Comment by fasouto** [comment]
Yes, it's something that is on my TODO list.

**Comment by fasouto** [comment]
It's done now.
