### ISSUE TITLE
Option for MySQL?

### ISSUE THREAD

**Issue by gamesbook** [fasouto/django-starter-template#6]
For a number of projects, MySQL is still required and not PostgreSQL - can you create a requirements file that does not require PostgreSQL  and allows for MySQL?

**Comment by fasouto** [comment]
Hi @gamesbook ! Thanks for your interest in the project

This project should be an starting point to create a django project and changing the database backend it's easy, just modify the requirements.txt and the settings. I think create a separate requirements file will create an extra overhead for very little benefit.

I was planning to include both in the requirements file but sometimes either `psycopg2` or `mysql-python` give problems during installation. Again too much trouble for very little gain.

Sorry for my broken English.

**Comment by gamesbook** [comment]
@fasouto Yes, I did create my own requirements file.  Perhaps the point is to not include **any** database-specific modules in the base requirements file at all; certainly the one for PostgreSQL generates an error on a machine without PostgreSQL already installed (you can test that yourself) which seems to defeat the point of a ready-to-use template.

**Comment by fasouto** [comment]
I think it's quite the opposite: remove the DB support defeat the point of having a ready-to-use template that covers the majority of the cases. While there are many sites that work without a database I think most Django projects are backed by one.

This project template is opinionated: some people won't need bootstrap, others won't need django-compressor.... if I removed everything else I will end with a barenones `django-admin startproject ` :smile:
