### ISSUE TITLE
The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10

### ISSUE THREAD

**Issue by Mec-iS** [fasouto/django-starter-template#9]
Warning at runtime, for future compatibility:
`?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.`

**Comment by fasouto** [comment]
Thanks @Mec-iS ! I just fixed this in c6edf099ee9bc22334e50992dab2f368214da53b
